use anyhow::{Context, Result};
use bench_core::RunDocument;
use std::fs;
use std::path::Path;

const ECHARTS: &str = include_str!("../../../assets/echarts.min.js");

pub fn render(document: &RunDocument, output: &Path) -> Result<()> {
    let data = serde_json::to_string(document)?.replace("</script", "<\\/script");
    let html = TEMPLATE
        .replace("/*__ECHARTS__*/", ECHARTS)
        .replace("/*__DATA__*/", &data);
    fs::write(output, html).with_context(|| format!("write {}", output.display()))
}

const TEMPLATE: &str = r#"<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>GUI benchmark report</title><style>
:root{color-scheme:light}*{box-sizing:border-box}body{margin:0;background:#fff;color:#000;font:15px/1.5 system-ui,sans-serif}
main{width:min(960px,calc(100% - 40px));margin:0 auto;padding:48px 0 80px}h1{font-size:30px;margin:0}h2{font-size:20px;margin:42px 0 4px}p{margin:4px 0 14px}.muted,.explanation{color:#444}
.controls{display:flex;gap:20px;align-items:end;flex-wrap:wrap;margin:32px 0;padding:16px 0;border-block:1px solid #000}.controls label{display:grid;gap:4px}.controls label:first-child{flex:1}.controls select{width:100%;min-width:180px;max-width:680px;background:#fff;color:#000;border:1px solid #000;padding:7px}
.summary-list{display:grid;gap:14px}.framework-summary{border:1px solid #000;border-top:4px solid}.framework-summary h3{margin:0;padding:8px 12px;border-bottom:1px solid #000;font-size:17px}.metric-grid{display:grid;grid-template-columns:repeat(6,1fr)}.metric{padding:10px 12px;border-right:1px solid #bbb}.metric:last-child{border:0}.metric .value{font-size:18px;font-variant-numeric:tabular-nums;margin-top:2px}.chart{width:100%;height:430px;border:1px solid #bbb}.quality{white-space:pre-wrap;border:1px solid #000;padding:14px;background:#fff;color:#000;font:14px/1.5 ui-monospace,monospace}
table{width:100%;border-collapse:collapse;margin:10px 0 24px;table-layout:fixed}th,td{text-align:left;vertical-align:top;border:1px solid #aaa;padding:7px 9px;overflow-wrap:anywhere}th{width:30%;font-weight:600;background:#f4f4f4}td{white-space:pre-wrap}code{font-size:.9em}
@media(max-width:700px){main{width:min(100% - 24px,960px);padding-top:24px}.metric-grid{grid-template-columns:1fr 1fr}.metric{border-bottom:1px solid #bbb}.metric:nth-child(even){border-right:0}.metric:nth-last-child(-n+2){border-bottom:0}.chart{height:340px}}
</style><script>/*__ECHARTS__*/</script></head><body>
<main><header><h1>GUI benchmark report</h1><div id="subtitle" class="muted"></div></header>
<div class="controls"><label>Scenario<select id="scenario"></select></label><label>Measurement mode<select id="mode"><option>headline</option><option>diagnostic</option></select></label></div>
<section><h2>At a glance</h2><p class="explanation">One summary row per framework for the selected scenario and measurement mode. Memory values are peaks across the completed repetitions.</p><div class="summary-list" id="summary"></div></section>
<section><h2>Frame-time distribution</h2><p class="explanation">The box spans the 25th to 75th percentile; its center is the median and its whiskers are the 5th and 95th percentiles. Lower and tighter is better.</p><div class="chart" id="dist"></div></section>
<section><h2>Frame time over the run</h2><p class="explanation">Every valid measurement frame is shown in sequence. This makes periodic stalls, warm-state drift, and isolated long frames visible.</p><div class="chart" id="timeline"></div></section>
<section><h2>Process and graphics memory</h2><p class="explanation">PSS estimates the process's proportional system-memory cost. Driver VRAM is the per-process resident allocation reported by DRM or NVML; framework GPU memory is the framework's own allocator report when available.</p><div class="chart" id="resources"></div></section>
<section><h2>Rendering pipeline</h2><p class="explanation">Median CPU wall time attributed to each diagnostic pipeline stage. These are submission-side timings, not on-device GPU execution or compositor time.</p><div class="chart" id="pipeline"></div></section>
<section><h2>Data quality</h2><div class="quality" id="quality"></div></section>
<section><h2>Benchmark configuration</h2><p class="explanation">The selected condition's neutral workload parameters and the sizes actually observed from the compositor.</p><table><tbody id="configuration"></tbody></table></section>
<section><h2>Reproducibility environment</h2><p class="explanation">Run provenance captured alongside the raw samples. Source dirty state matters when comparing results across revisions.</p><table><tbody id="environment"></tbody></table></section>
</main>
<script>const DATA=/*__DATA__*/;
const colors={zgui:'#0072b2',gpui:'#d55e00'}, names={zgui:'zgui',gpui:'GPUI-CE'}, stageColors=['#0072b2','#e69f00','#009e73','#cc79a7','#56b4e9','#d55e00','#f0e442','#7b61a8','#555'];
const $=id=>document.getElementById(id), ms=ns=>ns==null?null:ns/1e6, mb=b=>b==null?null:b/1048576;
function pct(a,p){a=a.filter(Number.isFinite).sort((x,y)=>x-y);if(!a.length)return null;return a[Math.min(a.length-1,Math.floor((a.length-1)*p))]}
function fmt(v,u=' ms'){return v==null?'—':v.toFixed(v<10?2:1)+u}
function rows(target,values){target.replaceChildren(...values.map(([key,value])=>{const row=document.createElement('tr'),heading=document.createElement('th'),cell=document.createElement('td');heading.textContent=key;cell.textContent=value??'—';row.append(heading,cell);return row}))}
const scenarios=[...new Map(DATA.conditions.map(c=>[c.scenario.id,c.scenario])).values()];
for(const s of scenarios){const o=document.createElement('option');o.value=s.id;o.textContent=`${s.workload} · ${s.nodes.toLocaleString()} nodes · ${s.topology} · ${Math.round(s.update_fraction*100)}%`; $('scenario').append(o)}
$('subtitle').textContent=`Run ${DATA.run_id} · ${new Date(DATA.started_at_unix_ms).toLocaleString()}`;
rows($('environment'),[['Run ID',DATA.run_id],['Started',new Date(DATA.started_at_unix_ms).toISOString()],['Command',DATA.command.join(' ')],['Schema version',String(DATA.schema_version)],['Operating system',DATA.host.os],['Kernel',DATA.host.kernel],['Architecture',DATA.host.architecture],['Display server',DATA.host.display_server],['CPU',DATA.host.cpu],['GPU',DATA.host.gpu.join('\n')],['Rust compiler',DATA.host.rustc],...Object.entries(DATA.sources).flatMap(([name,source])=>[[`${name} path`,source.path],[`${name} revision`,source.revision],[`${name} dirty`,String(source.dirty)]])]);
const charts=['dist','timeline','resources','pipeline'].map(id=>echarts.init($(id),null,{renderer:'canvas'}));
function selected(){return DATA.conditions.filter(c=>c.scenario.id===$('scenario').value&&c.mode===$('mode').value)}
function statusText(status){if(status==='complete')return'complete';if(status==='timed_out')return'timed out';if(status?.failed)return`failed: ${status.failed.message}`;return JSON.stringify(status)}
function base(){return{backgroundColor:'#fff',color:stageColors,textStyle:{color:'#000'},tooltip:{trigger:'axis',confine:true,backgroundColor:'#fff',borderColor:'#000',textStyle:{color:'#000'}},legend:{top:10,textStyle:{color:'#000'}},grid:{left:65,right:25,top:55,bottom:50},xAxis:{axisLabel:{color:'#000'},axisLine:{lineStyle:{color:'#000'}},splitLine:{show:false}},yAxis:{axisLabel:{color:'#000'},axisLine:{lineStyle:{color:'#000'}},splitLine:{lineStyle:{color:'#ddd'}}}}}
function render(){const cs=selected(), grouped=cs.reduce((a,c)=>((a[c.framework]??=[]).push(c),a),{}),spec=scenarios.find(s=>s.id===$('scenario').value);let vram=[];
for(const c of cs)vram.push(...c.resources.map(r=>mb(r.gpu_resident_bytes)));
const observed=[...new Set(cs.flatMap(c=>c.frames.filter(f=>f.phase==='measurement').map(f=>f.observed_width&&f.observed_height?`${f.observed_width}×${f.observed_height}`:null)).filter(Boolean))];rows($('configuration'),[['Scenario ID',spec?.id],['Workload',spec?.workload],['Nodes',spec?.nodes?.toLocaleString()],['Topology',spec?.topology],['Style complexity',spec?.style],['Update fraction',spec?`${(spec.update_fraction*100).toFixed(1)}%`:'—'],['Requested window',spec?`${spec.width}×${spec.height}`:'—'],['Observed window',observed.join(', ')||'—'],['Warmup frames',String(spec?.warmup_frames??'—')],['Measurement frames',String(spec?.sample_frames??'—')],['Seed',String(spec?.seed??'—')],['Mode',$('mode').value],['Frameworks',Object.keys(grouped).map(k=>names[k]).join(', ')||'—'],['Completed repetitions',`${cs.filter(c=>c.status==='complete').length}/${cs.length}`]]);
const maxFinite=a=>{a=a.filter(Number.isFinite);return a.length?Math.max(...a):null};const summaries=Object.entries(grouped).map(([k,v])=>{const card=document.createElement('article'),title=document.createElement('h3'),metrics=document.createElement('div'),statuses=[...new Set(v.map(c=>statusText(c.status)))];card.className='framework-summary';card.style.borderTopColor=colors[k];title.textContent=`${names[k]} — ${statuses.join(', ')}`;title.style.color=colors[k];metrics.className='metric-grid';const frameValues=v.flatMap(c=>c.frames.filter(f=>f.phase==='measurement'&&f.valid).map(f=>ms(f.frame_time_ns))),latencyValues=v.flatMap(c=>c.frames.filter(f=>f.phase==='measurement'&&f.valid).map(f=>ms(f.stimulus_latency_ns)));for(const [label,value] of [['Frame p50',fmt(pct(frameValues,.5))],['Frame p95',fmt(pct(frameValues,.95))],['Latency p95',fmt(pct(latencyValues,.95))],['Peak PSS',fmt(maxFinite(v.flatMap(c=>c.resources.map(r=>mb(r.pss_bytes)))),' MiB')],['Driver VRAM',fmt(maxFinite(v.flatMap(c=>c.resources.map(r=>mb(r.gpu_resident_bytes)))),' MiB')],['Framework GPU',fmt(maxFinite(v.flatMap(c=>c.frames.map(f=>mb(f.framework_memory?.gpu_bytes)))),' MiB')]]){const metric=document.createElement('div'),caption=document.createElement('div'),number=document.createElement('div');metric.className='metric';caption.className='muted';caption.textContent=label;number.className='value';number.textContent=value;metric.append(caption,number);metrics.append(metric)}card.append(title,metrics);return card});$('summary').replaceChildren(...summaries);
let o=base();o.xAxis={type:'value',name:'milliseconds',axisLabel:{color:'#000'}};o.yAxis={type:'category',data:Object.keys(grouped).map(k=>names[k]),axisLabel:{color:'#000'}};o.series=[{name:'frame time',type:'boxplot',data:Object.entries(grouped).map(([k,v])=>{const a=v.flatMap(c=>c.frames.filter(f=>f.phase==='measurement'&&f.valid).map(f=>ms(f.frame_time_ns))).filter(Number.isFinite);return{value:[pct(a,.05),pct(a,.25),pct(a,.5),pct(a,.75),pct(a,.95)],itemStyle:{color:colors[k]}}})}];charts[0].setOption(o,true);
o=base();o.xAxis={type:'value',name:'frame',axisLabel:{color:'#000'}};o.yAxis={type:'value',name:'ms',axisLabel:{color:'#000'}};o.series=cs.map(c=>({name:`${names[c.framework]} #${c.repetition+1}`,type:'line',showSymbol:false,sampling:'lttb',data:c.frames.filter(f=>f.phase==='measurement'&&f.valid).map(f=>[f.sequence,ms(f.frame_time_ns)]),lineStyle:{color:colors[c.framework],type:c.repetition%2?'dashed':'solid'}}));charts[1].setOption(o,true);
o=base();o.xAxis={type:'value',name:'seconds',axisLabel:{color:'#000'}};o.yAxis={type:'value',name:'MiB',axisLabel:{color:'#000'}};o.series=cs.flatMap(c=>{const label=`${names[c.framework]} #${c.repetition+1}`;return[{name:`${label} PSS`,type:'line',showSymbol:false,data:c.resources.map(r=>[r.timestamp_ns/1e9,mb(r.pss_bytes)]),lineStyle:{color:colors[c.framework]}},{name:`${label} driver VRAM`,type:'line',showSymbol:false,data:c.resources.map(r=>[r.timestamp_ns/1e9,mb(r.gpu_resident_bytes)]),lineStyle:{color:colors[c.framework],type:'dashed'}},{name:`${label} framework GPU`,type:'line',showSymbol:false,data:c.frames.map(f=>[f.timestamp_ns/1e9,mb(f.framework_memory?.gpu_bytes)]),lineStyle:{color:colors[c.framework],type:'dotted'}}]});charts[2].setOption(o,true);
const stages=['view_build_ns','style_ns','layout_ns','prepaint_ns','paint_ns','gpu_prepare_ns','command_encode_ns','queue_submit_ns','present_ns'];o=base();o.xAxis={type:'category',data:Object.keys(grouped).map(k=>names[k]),axisLabel:{color:'#000'}};o.yAxis={type:'value',name:'ms',axisLabel:{color:'#000'}};o.series=stages.map(stage=>({name:stage.replace('_ns',''),type:'bar',stack:'pipeline',data:Object.entries(grouped).map(([k,v])=>pct(v.flatMap(c=>c.frames.map(f=>ms(f.pipeline[stage]))),.5))}));charts[3].setOption(o,true);
const missing=[...new Set(cs.flatMap(c=>c.warnings??[]))];for(const c of cs.filter(c=>c.status!=='complete'))missing.push(`${names[c.framework]} repetition ${c.repetition+1}: ${statusText(c.status)}; charts show any partial samples that were captured.`);if(!vram.some(Number.isFinite))missing.push('VRAM is unavailable: neither DRM fdinfo nor NVML exposed a per-process resident-memory counter.');if($('mode').value==='headline')missing.push('Pipeline stages are intentionally disabled in headline mode; select diagnostic mode after collecting diagnostic runs.');$('quality').textContent=`Data quality\n${missing.length?missing.map(x=>'• '+x).join('\n'):'• All requested counters were present.'}\n• “GPU” stages are CPU submission timings unless a sample explicitly sets device_gpu_timestamps=true.\n• Raw samples are embedded in this report and preserved in the source JSON.`;
}
$('scenario').onchange=render;$('mode').onchange=render;window.onresize=()=>charts.forEach(c=>c.resize());render();</script></body></html>"#;
